/**
 * 大体积美术使用内容寻址 CDN；URL 为每次上传生成的不可变地址，可交给浏览器和 Cocos 缓存。
 * 逻辑仍使用 resources 路径作为稳定 key，避免 CDN 迁移波及业务配置。
 */
export const REMOTE_SPRITE_URLS: Readonly<Record<string, string>> = {
    'art/bosses/shanxiao/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/33e1-audiotest/87/4A/GAqSpGcORnNLAABApgACEGbx.png',
    'art/characters/qinglan/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/6be9-audiotest/C6/DE/GAqSoUUORnNLAAAp8QACEGby.png',
    'art/enemies/fox-spirit/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/9e46-audiotest/87/0C/GAqSpGcORnNMAAAiwwACEGb1.png',
    'art/enemies/jiangshi/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/436c-audiotest/07/50/GAqSoUUORnNMAAAdbgACEGb0.png',
    'art/enemies/mountain-spirit/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/1abd-audiotest/6C/1C/GAqSpGcORnNMAAAiIwACEGbz.png',
    'art/relics/xianxia-relics_00/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/c999-audiotest/7E/D8/GAqSoUUORnNIAAANbQACEGbl.png',
    'art/relics/xianxia-relics_02/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/3d47-audiotest/F3/A0/GAqSpGcORnNIAAASIAACEGbn.png',
    'art/relics/xianxia-relics_04/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/482a-audiotest/50/0A/GAqSpGcORnNJAAAaiAACEGbr.png',
    'art/relics/xianxia-relics_05/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/05c2-audiotest/B5/0E/GAqSoUUORnNKAAAcEgACEGbs.png',
    'art/relics/xianxia-relics_06/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/12f2-audiotest/24/49/GAqSoUUORnNJAAASdAACEGbq.png',
    'art/relics/xianxia-relics_11/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/78bb-audiotest/BB/02/GAqSpGcORnNKAAAXHAACEGbt.png',
    'art/relics/xianxia-relics_12/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/155f-audiotest/53/26/GAqSpGcORnNJAAAXyQACEGbp.png',
    'art/relics/xianxia-relics_15/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/6359-audiotest/EE/A4/GAqSpGcORnNIAAAZwAACEGbk.png',
    'art/relics/xianxia-relics_17/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/d9e0-audiotest/C6/AC/GAqSoUUORnNJAAAZ6QACEGbo.png',
    'art/relics/xianxia-relics_18/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/7ca7-audiotest/B4/15/GAqSoUUORnNHAAAXwgACEGbj.png',
    'art/relics/xianxia-relics_19/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/8406-audiotest/7A/32/GAqSoUUORnNHAAARIAACEGbh.png',
    'art/relics/xianxia-relics_20/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/bc30-audiotest/8B/8B/GAqSpGcORnNGAAAWFAACEGbe.png',
    'art/relics/xianxia-relics_21/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/38bf-audiotest/CC/E0/GAqSoUUORnNGAAAcnQACEGbf.png',
    'art/relics/xianxia-relics_23/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/7cc3-audiotest/E0/1F/GAqSpGcORnNGAAASUwACEGbg.png',
    'art/relics/xianxia-relics_24/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/d452-audiotest/86/45/GAqSpGcORnNHAAATHgACEGbi.png',
    'art/ui/cultivation-sheet-frame-v1/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/4a05-audiotest/6D/D6/GAqSpGcORnNFAAob5gACEGbc.png',
    'art/ui/wave-crest-v1/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/c1e0-audiotest/9B/24/GAqSoUUORnNFAACD_gACEGbd.png',
    'art/vfx/dao-sword-aura/dao-sword-edge-v2/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/db96-audiotest/1C/4E/GAqSoUUOUM9KAAET2AACEUmZ.png',
    'art/vfx/dao-sword-aura/dao-sword-mystic-v2/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/66bd-audiotest/CA/C4/GAqSoUUOUM9JAAFT8AACEUmX.png',
    'art/vfx/dao-sword-aura/dao-sword-vitality-v2/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/ed2b-audiotest/E8/E1/GAqSpGcOUM9KAAEJLQACEUmY.png',
    'art/obstacles/bamboo-barricade/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/69ad-audiotest/7C/E6/GAqSpGcORdXgAAVQ5QACEFeE.png',
    'art/ui/qinglan-hud-portrait-transparent-v2/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/7a55-audiotest/4F/A3/GAqSoUUORdXgAAH3VgACEFeF.png',
    'art/backgrounds/frozen-ruins/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/a4e8-audiotest/DB/D0/GAqSpGcORdXhAAs5kQACEFeG.png',
    'art/backgrounds/qingshi-road/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/b8b1-audiotest/E4/16/GAqSoUUORdXiAAgg0wACEFeH.png',
    'art/backgrounds/bamboo-ambush/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/11d9-audiotest/4E/F3/GAqSpGcORdXiABAAAAACEFeI.png',
    'art/bosses/shanxiao-actions/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/bc27-audiotest/E0/7C/GAqSpGcORdXjAAeU1wACEFeK.png',
    'art/bosses/hanyuan-shanxiao-actions/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/bf04-audiotest/A6/11/GAqSoUUORdXkAAgeWwACEFeL.png',
    'art/characters/qinglan-actions/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/8fa8-audiotest/AC/3F/GAqSpGcORdXkAAbpNwACEFeM.png',
    'art/effects/qingshi-stele-commit/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/4383-audiotest/B3/EB/GAqSoUUORdXlAAnFvgACEFeN.png',
    'art/effects/frost-seal-commit/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/5ed0-audiotest/79/58/GAqSpGcORdXmAAQYugACEFeO.png',
    'art/effects/bamboo-burn-commit/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/4c4f-audiotest/8F/3C/GAqSoUUORdXmAAbVbwACEFeP.png',
    'art/effects/bamboo-shadow-commit/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/c21e-audiotest/4F/39/GAqSpGcORdXnAAHN6QACEFeQ.png',
    'art/effects/hanyuan-frost-impact/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/fd45-audiotest/B0/3F/GAqSoUUORdXnAAk30AACEFeR.png',
    'art/effects/qingshi-spring-commit/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/04cb-audiotest/6B/A1/GAqSpGcORdXoAANEFAACEFeS.png',
    'art/effects/frost-tide-commit/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/636e-audiotest/19/6B/GAqSoUUORdXpAAS_1QACEFeT.png',
    'art/enemies/bamboo-warden/spriteFrame': 'https://audiopaytest.cos.tx.xmcdn.com/storages/d990-audiotest/0D/ED/GAqSpGcORdXqAAYAbQACEFeU.png',
};
